### ISSUE TITLE
No longer works 2024

### ISSUE THREAD

**Issue by aspiring3dmodeler** [camenduru/PanoHead-colab#11]
First step seems to work but the second block of code doesn't work

I think this is the problem:

https://github.com/SizheAn/PanoHead/issues/49

**Comment by Animus777** [comment]
After running first cell, create a new one ("+ Code" a the top left of Colab), paste this:
 
 `!pip install --force-reinstall numpy==1.23.5` 

and run it. After that you will be able to run second block and all the others.

**Comment by aspiring3dmodeler** [comment]
> After running first cell, create a new one ("+ Code" a the top left of Colab), paste this:
> 
> `!pip install --force-reinstall numpy==1.23.5`
> 
> and run it. After that you will be able to run second block and all the others.

Sorry im slow, do you have a video of how to do it? :) it want's me to restart runtime

**Comment by Animus777** [comment]
Just agree to restart runtime when it asks you. When restart is complete, you can run second block (DONT run first one again).

**Comment by nwy140** [comment]
It's 2025 now

And I'm still facing even after running !pip install --force-reinstall numpy==1.23.5

`
/content/3DDFA_V2
  0% 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/3DDFA_V2/recrop_images.py", line 322, in <module>
    main(args)
  File "/content/3DDFA_V2/recrop_images.py", line 291, in main
    cv2.imwrite(os.path.join(args.out_dir, os.path.basename(img_path).replace(".png",".jpg")), cropped_img)
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:798: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'

cp: cannot stat '/content/3DDFA_V2/crop_samples/img/*': No such file or directory
`
